# Generated by Django 5.1.1 on 2024-09-24 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operator',
            old_name='photo',
            new_name='name',
        ),
    ]
