# Generated by Django 5.1.1 on 2024-09-26 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_photo_operator_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='organization',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
