# Generated by Django 5.1.1 on 2024-09-28 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_operator_organization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operator',
            old_name='name',
            new_name='names',
        ),
    ]
