# Generated by Django 5.1.1 on 2024-09-28 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_rename_name_operator_names'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operator',
            old_name='names',
            new_name='name',
        ),
    ]
