# Generated by Django 5.1.1 on 2024-10-07 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_alter_note_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSpotsMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.IntegerField()),
                ('width', models.IntegerField()),
                ('orientation', models.CharField(choices=[('horizontal', 'Horizontal'), ('vertical', 'Vertical')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ParkingSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_axis', models.IntegerField()),
                ('y_axis', models.IntegerField()),
                ('sensor_status', models.CharField(choices=[('used', 'Used'), ('unused', 'Unused')], max_length=10)),
                ('status', models.CharField(choices=[('sensor', 'Sensor Status'), ('maintenance', 'Maintenance'), ('unavailable', 'Unavailable'), ('road', 'Road')], default='sensor', max_length=20)),
                ('parking_spots_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.parkingspotsmap')),
            ],
        ),
        migrations.CreateModel(
            name='VirtualSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('used', 'Used'), ('unused', 'Unused')], default='unused', max_length=10)),
                ('parking_spot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.parkingspot')),
            ],
        ),
    ]
