# Generated by Django 5.1.1 on 2024-10-20 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_parkingspotsmap_email_parkingspotsmap_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspotsmap',
            name='loc',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
