# Generated by Django 5.1.1 on 2024-11-24 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_parkingspotsmap_loc"),
    ]

    operations = [
        migrations.CreateModel(
            name="MapReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parking_map",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.parkingspotsmap",
                    ),
                ),
            ],
        ),
    ]
