# Generated by Django 5.1.1 on 2024-11-24 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_mapreport"),
    ]

    operations = [
        migrations.AddField(
            model_name="mapreport",
            name="font_family",
            field=models.CharField(default="Arial", max_length=50),
        ),
        migrations.AddField(
            model_name="mapreport",
            name="font_size",
            field=models.CharField(default="16px", max_length=10),
        ),
        migrations.AddField(
            model_name="mapreport",
            name="font_style",
            field=models.CharField(default="normal", max_length=10),
        ),
        migrations.AddField(
            model_name="mapreport",
            name="font_weight",
            field=models.CharField(default="normal", max_length=10),
        ),
        migrations.AddField(
            model_name="mapreport",
            name="text_align",
            field=models.CharField(default="left", max_length=10),
        ),
    ]
